# Generated by Django 5.0.2 on 2026-04-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmc_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventLog',
        ),
    ]
